wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682372595.195228
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.15.0
      6: 4.24.0
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: valid_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_acc
      5: 1
      6:
      - 1
model:
  desc: null
  value: null
